#!/bin/bash
set -e

docker run --rm \
       --name plone-dev --net=backend -p 8080:8080 \
       -e PLONE_ADDONS="collective.easyform" \
       -e PLONE_DEVELOP="src/collective.easyform" \
       -v $(pwd)/data/:/data/ \
       -v $(pwd)/src:/plone/instance/src \
       plonews:5.2.2-python37 fg
