version: '3'

services:
  haproxy:
    image: eeacms/haproxy
    ports:
    - 8080:5000
    - 1936:1936
    depends_on:
    - plone
    environment:
      BACKENDS: "plone"
      BACKENDS_PORT: "8080"
      DNS_ENABLED: "True"
      TZ: "Europe/Berlin"
    networks:
      - backend

  plone:
    image: plonews:5.2.2-python37
    depends_on:
      #- memcached
      - zeoserver
    environment:
      ZEO_ADDRESS: "zeoserver:8080"
      #MEMCACHE_SERVER: "memcached:11211"
      TZ: "Europe/Berlin"
    #command: ['fg']
    volumes:
      - ./src/:/plone/instance/src/
    networks:
      - backend

  zeoserver:
    image: plonews:5.2.2-python37
    container_name: zeoserver
    command: zeo
    volumes:
      - ./data/:/data/
    environment:
      TZ: "Europe/Berlin"
    networks:
      - backend

  memcached:
    image: memcached:latest
    command:
    - "-m"
    - "1024"
    environment:
      TZ: "Europe/Berlin"
    networks:
      - backend


networks:
  backend:
    name: backend

volumes:
  data:
